/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalsyatem;

/**
 *
 * @author Hp
 */
public class AdminFram extends javax.swing.JFrame {

    /**
     * Creates new form AdminFram
     */
    public AdminFram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        reception = new javax.swing.JMenu();
        reception_menagement = new javax.swing.JMenuItem();
        employee = new javax.swing.JMenu();
        emp_menagemant = new javax.swing.JMenuItem();
        customer = new javax.swing.JMenu();
        customer_management = new javax.swing.JMenuItem();
        vehicle = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu5.setText("jMenu5");

        jMenu8.setText("jMenu8");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setToolTipText("");
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        reception.setText("Reception");
        reception.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptionActionPerformed(evt);
            }
        });

        reception_menagement.setText("Reception Management");
        reception_menagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reception_menagementActionPerformed(evt);
            }
        });
        reception.add(reception_menagement);

        jMenuBar1.add(reception);

        employee.setText("Employee");
        employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeActionPerformed(evt);
            }
        });

        emp_menagemant.setText("Employee Management");
        emp_menagemant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_menagemantActionPerformed(evt);
            }
        });
        employee.add(emp_menagemant);

        jMenuBar1.add(employee);

        customer.setText("Customer");

        customer_management.setText("Customer Management");
        customer_management.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_managementActionPerformed(evt);
            }
        });
        customer.add(customer_management);

        jMenuBar1.add(customer);

        vehicle.setText("Vehicle");

        jMenuItem3.setText("Vehicle Management");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        vehicle.add(jMenuItem3);

        jMenuBar1.add(vehicle);

        logout.setText("Logout");

        jMenuItem4.setText("Logout");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        logout.add(jMenuItem4);

        jMenuBar1.add(logout);
        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 902, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void receptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptionActionPerformed
        // TODO add your handling code here:
        Reception recep=new Reception();
        recep.setVisible(true);
    }//GEN-LAST:event_receptionActionPerformed

    private void employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_employeeActionPerformed

    private void reception_menagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reception_menagementActionPerformed
        // TODO add your handling code here:
        Reception recep=new Reception();
        recep.setVisible(true);
    }//GEN-LAST:event_reception_menagementActionPerformed

    private void emp_menagemantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_menagemantActionPerformed
        // TODO add your handling code here:
       EmployeeMenagement Emp= new EmployeeMenagement();
       Emp.setVisible(true);
    }//GEN-LAST:event_emp_menagemantActionPerformed

    private void customer_managementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_managementActionPerformed
        // TODO add your handling code here:
          CustomerMenagement cus= new CustomerMenagement();
       cus.setVisible(true);
    }//GEN-LAST:event_customer_managementActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        VehicleMenagement veh=new VehicleMenagement();
        veh.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        CarRentalSyatem log=new CarRentalSyatem();
        log.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu customer;
    private javax.swing.JMenuItem customer_management;
    private javax.swing.JMenuItem emp_menagemant;
    private javax.swing.JMenu employee;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu logout;
    private javax.swing.JMenu reception;
    private javax.swing.JMenuItem reception_menagement;
    private javax.swing.JMenu vehicle;
    // End of variables declaration//GEN-END:variables
}
